using Godot;

namespace LegoSpaceRTS.UI;

/// <summary>
/// A compact, code-native tactical portrait. It deliberately reads as a
/// schematic generated by the command console rather than as temporary text
/// or as an implied final piece of character art.
/// </summary>
public partial class HudPortraitView : Control
{
    private PortraitKind _kind;
    private Color _background = new("0b1016");
    private Color _primary = new("b47a3a");
    private Color _secondary = new("147f79");
    private Color _muted = new("aab4b8");
    private bool _hasSelection;

    public HudPortraitView()
    {
        MouseFilter = MouseFilterEnum.Ignore;
        ClipContents = true;
    }

    public void ApplyProfile(M7HudProfile profile)
    {
        _background = Parse(profile.Colors.Recessed, new Color("0b1016"));
        _muted = Parse(profile.Colors.TextMuted, new Color("aab4b8"));
        _primary = profile.ArtSkin.Enabled
            ? HudFactionChrome.AccentForFaction(profile.ArtSkin.Faction)
            : Parse(profile.Colors.Accent, new Color("e6ad28"));
        _secondary = profile.ArtSkin.Enabled
            ? HudFactionChrome.SecondaryAccentForFaction(profile.ArtSkin.Faction)
            : Parse(profile.Colors.Selection, new Color("5fc4d8"));
        QueueRedraw();
    }

    public void SetSelection(HudSelectionFrame selection)
    {
        _hasSelection = selection.Count > 0 || selection.HealthPercent >= 0 ||
            !selection.Title.Equals("NO SELECTION", StringComparison.OrdinalIgnoreCase);
        _kind = InferKind(selection);
        QueueRedraw();
    }

    public override void _Notification(int what)
    {
        if (what == NotificationResized) QueueRedraw();
    }

    public override void _Draw()
    {
        if (Size.X < 24f || Size.Y < 24f) return;

        Rect2 screen = new(new Vector2(1f, 1f), Size - new Vector2(2f, 2f));
        DrawRect(screen, _background.Darkened(0.10f));
        DrawGrid(screen);
        DrawFrame(screen);

        Rect2 glyphArea = new(
            new Vector2(Size.X * 0.10f, Size.Y * 0.12f),
            new Vector2(Size.X * 0.80f, Size.Y * 0.72f));
        if (!_hasSelection)
        {
            DrawEmpty(glyphArea);
            return;
        }

        switch (_kind)
        {
            case PortraitKind.Structure:
                DrawStructure(glyphArea);
                break;
            case PortraitKind.Group:
                DrawGroup(glyphArea);
                break;
            case PortraitKind.Transforming:
                DrawTransformation(glyphArea);
                break;
            default:
                DrawVehicle(glyphArea, 1f);
                break;
        }

        DrawReadoutTicks(screen);
    }

    public static string ConciseCaption(HudSelectionFrame selection)
    {
        string[] lines = selection.PortraitCaption.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        string caption = lines.Length > 0 ? lines[^1] : selection.Title;
        if (string.IsNullOrWhiteSpace(caption)) return "NO SELECTION";
        return caption.Length <= 24 ? caption : $"{caption[..21]}…";
    }

    private static PortraitKind InferKind(HudSelectionFrame selection)
    {
        string source = $"{selection.Title}|{selection.Subtitle}|{selection.PortraitCaption}|{selection.StatusText}".ToUpperInvariant();
        if (source.Contains("TRANSFORM", StringComparison.Ordinal) || source.Contains('⇄'))
            return PortraitKind.Transforming;

        string[] structureTerms =
        {
            "STRUCTURE", "BUILDING", "PLANT", " STATION", "SERVICE BAY", "FACILIT", " HQ", "CORE", "PROCESSING"
        };
        for (int i = 0; i < structureTerms.Length; i++)
            if (source.Contains(structureTerms[i], StringComparison.Ordinal)) return PortraitKind.Structure;

        return selection.Count > 1 || selection.Groups.Count > 0
            ? PortraitKind.Group
            : PortraitKind.Vehicle;
    }

    private void DrawGrid(Rect2 screen)
    {
        Color minor = new(_secondary, 0.075f);
        Color major = new(_secondary, 0.14f);
        float spacing = Mathf.Clamp(Mathf.Min(screen.Size.X, screen.Size.Y) / 7f, 9f, 18f);
        int line = 0;
        for (float x = screen.Position.X + spacing; x < screen.End.X; x += spacing, line++)
            DrawLine(new Vector2(x, screen.Position.Y), new Vector2(x, screen.End.Y), line % 4 == 3 ? major : minor, 1f);
        line = 0;
        for (float y = screen.Position.Y + spacing; y < screen.End.Y; y += spacing, line++)
            DrawLine(new Vector2(screen.Position.X, y), new Vector2(screen.End.X, y), line % 4 == 3 ? major : minor, 1f);
    }

    private void DrawFrame(Rect2 screen)
    {
        Color primary = new(_primary, 0.78f);
        Color secondary = new(_secondary, 0.56f);
        float corner = Mathf.Clamp(Mathf.Min(screen.Size.X, screen.Size.Y) * 0.10f, 7f, 15f);
        DrawLine(screen.Position, screen.Position + new Vector2(corner, 0f), primary, 2f, true);
        DrawLine(screen.Position, screen.Position + new Vector2(0f, corner), primary, 2f, true);
        DrawLine(new Vector2(screen.End.X - corner, screen.Position.Y), new Vector2(screen.End.X, screen.Position.Y), primary, 2f, true);
        DrawLine(new Vector2(screen.End.X, screen.Position.Y), new Vector2(screen.End.X, screen.Position.Y + corner), primary, 2f, true);
        DrawLine(new Vector2(screen.Position.X, screen.End.Y - corner), new Vector2(screen.Position.X, screen.End.Y), secondary, 2f, true);
        DrawLine(new Vector2(screen.Position.X, screen.End.Y), new Vector2(screen.Position.X + corner, screen.End.Y), secondary, 2f, true);
        DrawLine(new Vector2(screen.End.X - corner, screen.End.Y), screen.End, secondary, 2f, true);
        DrawLine(new Vector2(screen.End.X, screen.End.Y - corner), screen.End, secondary, 2f, true);
    }

    private void DrawReadoutTicks(Rect2 screen)
    {
        Color ticks = new(_primary, 0.72f);
        float length = Mathf.Clamp(screen.Size.X * 0.045f, 4f, 7f);
        for (int i = 0; i < 5; i++)
        {
            float x = screen.End.X - 7f - i * (length + 3f);
            DrawLine(new Vector2(x, screen.End.Y - 6f), new Vector2(x + length, screen.End.Y - 6f), ticks, 1.5f);
        }
        DrawCircle(new Vector2(screen.Position.X + 8f, screen.End.Y - 7f), 2.2f, new Color(_secondary, 0.85f));
    }

    private void DrawEmpty(Rect2 area)
    {
        Color muted = new(_muted, 0.28f);
        Vector2 center = area.GetCenter();
        float radius = Mathf.Min(area.Size.X, area.Size.Y) * 0.23f;
        DrawArc(center, radius, 0f, Mathf.Tau, 40, muted, 1.5f, true);
        DrawLine(center - new Vector2(radius * 0.55f, 0f), center + new Vector2(radius * 0.55f, 0f), muted, 1f);
        DrawLine(center - new Vector2(0f, radius * 0.55f), center + new Vector2(0f, radius * 0.55f), muted, 1f);
    }

    private void DrawVehicle(Rect2 area, float opacity)
    {
        DrawVehicleAt(area.GetCenter(), new Vector2(area.Size.X * 0.76f, area.Size.Y * 0.66f), opacity);
    }

    private void DrawVehicleAt(Vector2 center, Vector2 size, float opacity)
    {
        float left = center.X - size.X * 0.5f;
        float top = center.Y - size.Y * 0.5f;
        Color outline = new(_primary, 0.92f * opacity);
        Color fill = new(_primary, 0.15f * opacity);
        Color secondary = new(_secondary, 0.88f * opacity);
        float trackWidth = size.X * 0.16f;
        Rect2 leftTrack = new(new Vector2(left, top + size.Y * 0.14f), new Vector2(trackWidth, size.Y * 0.72f));
        Rect2 rightTrack = new(new Vector2(left + size.X - trackWidth, top + size.Y * 0.14f), new Vector2(trackWidth, size.Y * 0.72f));
        DrawRect(leftTrack, new Color(_secondary, 0.18f * opacity));
        DrawRect(leftTrack, secondary, false, 1.5f, true);
        DrawRect(rightTrack, new Color(_secondary, 0.18f * opacity));
        DrawRect(rightTrack, secondary, false, 1.5f, true);

        Vector2[] body =
        {
            new(left + size.X * 0.24f, top + size.Y * 0.18f),
            new(left + size.X * 0.76f, top + size.Y * 0.18f),
            new(left + size.X * 0.86f, top + size.Y * 0.66f),
            new(left + size.X * 0.66f, top + size.Y * 0.90f),
            new(left + size.X * 0.34f, top + size.Y * 0.90f),
            new(left + size.X * 0.14f, top + size.Y * 0.66f)
        };
        DrawColoredPolygon(body, fill);
        DrawClosed(body, outline, 2f);

        Rect2 cockpit = new(
            new Vector2(left + size.X * 0.35f, top + size.Y * 0.26f),
            new Vector2(size.X * 0.30f, size.Y * 0.27f));
        DrawRect(cockpit, new Color(_secondary, 0.24f * opacity));
        DrawRect(cockpit, secondary, false, 1.5f, true);
        DrawLine(new Vector2(center.X, cockpit.End.Y), new Vector2(center.X, top + size.Y * 0.86f), outline, 1.5f, true);
        DrawCircle(new Vector2(center.X, top + size.Y * 0.70f), Mathf.Max(2f, size.X * 0.035f), secondary);
    }

    private void DrawGroup(Rect2 area)
    {
        Vector2 size = new(area.Size.X * 0.46f, area.Size.Y * 0.39f);
        DrawVehicleAt(area.GetCenter() + new Vector2(-area.Size.X * 0.20f, area.Size.Y * 0.15f), size, 0.60f);
        DrawVehicleAt(area.GetCenter() + new Vector2(area.Size.X * 0.20f, area.Size.Y * 0.15f), size, 0.72f);
        DrawVehicleAt(area.GetCenter() + new Vector2(0f, -area.Size.Y * 0.14f), size * 1.08f, 1f);
    }

    private void DrawStructure(Rect2 area)
    {
        float left = area.Position.X + area.Size.X * 0.10f;
        float top = area.Position.Y + area.Size.Y * 0.08f;
        float width = area.Size.X * 0.80f;
        float height = area.Size.Y * 0.78f;
        Color outline = new(_primary, 0.94f);
        Color secondary = new(_secondary, 0.88f);
        Rect2 foundation = new(new Vector2(left, top + height * 0.77f), new Vector2(width, height * 0.18f));
        DrawRect(foundation, new Color(_primary, 0.17f));
        DrawRect(foundation, outline, false, 2f, true);

        Vector2[] tower =
        {
            new(left + width * 0.18f, top + height * 0.77f),
            new(left + width * 0.24f, top + height * 0.25f),
            new(left + width * 0.38f, top + height * 0.10f),
            new(left + width * 0.72f, top + height * 0.20f),
            new(left + width * 0.82f, top + height * 0.77f)
        };
        DrawColoredPolygon(tower, new Color(_primary, 0.13f));
        DrawClosed(tower, outline, 2f);

        Rect2 core = new(new Vector2(left + width * 0.37f, top + height * 0.37f), new Vector2(width * 0.30f, height * 0.24f));
        DrawRect(core, new Color(_secondary, 0.24f));
        DrawRect(core, secondary, false, 1.5f, true);
        DrawLine(new Vector2(left + width * 0.28f, top + height * 0.70f), new Vector2(left + width * 0.72f, top + height * 0.70f), secondary, 1.5f);
        DrawLine(new Vector2(left + width * 0.55f, top + height * 0.18f), new Vector2(left + width * 0.55f, top), outline, 1.5f);
        DrawCircle(new Vector2(left + width * 0.55f, top), Mathf.Max(2f, width * 0.025f), secondary);
    }

    private void DrawTransformation(Rect2 area)
    {
        Vector2 leftCenter = area.GetCenter() - new Vector2(area.Size.X * 0.24f, 0f);
        DrawVehicleAt(leftCenter, new Vector2(area.Size.X * 0.40f, area.Size.Y * 0.43f), 0.70f);

        Vector2 center = area.GetCenter() + new Vector2(area.Size.X * 0.24f, -area.Size.Y * 0.02f);
        Vector2 span = new(area.Size.X * 0.21f, area.Size.Y * 0.27f);
        Vector2[] aircraft =
        {
            center - new Vector2(0f, span.Y),
            center + new Vector2(span.X * 0.28f, -span.Y * 0.18f),
            center + new Vector2(span.X, span.Y * 0.36f),
            center + new Vector2(span.X * 0.16f, span.Y * 0.18f),
            center + new Vector2(0f, span.Y),
            center + new Vector2(-span.X * 0.16f, span.Y * 0.18f),
            center + new Vector2(-span.X, span.Y * 0.36f),
            center + new Vector2(-span.X * 0.28f, -span.Y * 0.18f)
        };
        DrawColoredPolygon(aircraft, new Color(_secondary, 0.18f));
        DrawClosed(aircraft, new Color(_secondary, 0.95f), 2f);
        float arrowX = area.GetCenter().X;
        DrawLine(new Vector2(arrowX - 5f, area.End.Y - 10f), new Vector2(arrowX + 5f, area.End.Y - 10f), new Color(_primary, 0.88f), 1.5f, true);
        DrawLine(new Vector2(arrowX + 5f, area.End.Y - 10f), new Vector2(arrowX + 1f, area.End.Y - 14f), new Color(_primary, 0.88f), 1.5f, true);
    }

    private void DrawClosed(Vector2[] points, Color color, float width)
    {
        Vector2[] closed = new Vector2[points.Length + 1];
        Array.Copy(points, closed, points.Length);
        closed[^1] = points[0];
        DrawPolyline(closed, color, width, true);
    }

    private static Color Parse(string html, Color fallback) => Color.HtmlIsValid(html) ? new Color(html) : fallback;

    private enum PortraitKind : byte
    {
        Vehicle,
        Group,
        Structure,
        Transforming
    }
}
