using System.Text;

namespace LegoSpaceRTS.SimCore
{
/// <summary>Development-only ordered state text used to localize deterministic hash divergence.</summary>
public static class AuthoritativeStateDumper
{
    public static string Dump(SimulationWorld world)
    {
        StringBuilder b=new StringBuilder(8192);
        b.Append("tick=").Append(world.Tick.Value).Append(" nextEntity=").Append(world.Entities.NextEntityValue)
            .Append(" map=").Append(world.Map.Id.Value).Append(" topology=").Append(world.Map.TopologyVersion)
            .Append(" tubeTopology=").Append(world.TubeTopologyRevision).Append(" tubeSegmentation=").Append(world.TubeSegmentationRevision).AppendLine();
        for(int player=0;player<world.PlayerCount;player++){OperationsCapacityState capacity=world.GetOperationsCapacity((byte)player);AlienChargeState charge=world.GetAlienCharge((byte)player);b.Append("player ").Append(player).Append(" oc=").Append(capacity.Active).Append('+').Append(capacity.Reserved).Append('/').Append(capacity.Maximum).Append(" charge=").Append(charge.CurrentMillicharge).Append('/').Append(charge.MaximumMillicharge).Append(" chargeGen=").Append(charge.GenerationMillichargePerSecond).Append(" resonanceInit=").Append(charge.ResonanceInitiationUnlocked?1:0);for(int ei=0;ei<world.Entities.Alive.Count;ei++){EntityId root=world.Entities.Alive[ei];if(world.Entities.EnergyDomain.TryGet(root,out EnergyDomain energy)&&world.Entities.Ownership.TryGet(root,out Ownership owner)&&owner.PlayerSlot==player)b.Append(" energy=").Append(energy.Reserve.Raw).Append('/').Append(energy.ReserveCapacity.Raw).Append(" flow=").Append(energy.GenerationPerSecond).Append('-').Append(energy.ContinuousDemandPerSecond);}b.AppendLine();}
        var alive=world.Entities.Alive;
        for(int i=0;i<alive.Count;i++)
        {
            EntityId id=alive[i]; b.Append("entity ").Append(id.Value);
            if(world.Entities.Ownership.TryGet(id,out Ownership o))b.Append(" owner=").Append(o.PlayerSlot);
            if(world.Entities.Transform.TryGet(id,out SimTransform t))b.Append(" pos=").Append(t.Position.X.Raw).Append(',').Append(t.Position.Y.Raw).Append(" angle=").Append(t.Orientation.Raw);
            if(world.Entities.Movement.TryGet(id,out Movement m))b.Append(" speed=").Append(m.CurrentSpeed.Raw).Append(" vel=").Append(m.CurrentVelocity.X.Raw).Append(',').Append(m.CurrentVelocity.Y.Raw).Append(" desired=").Append(m.DesiredMovement.X.Raw).Append(',').Append(m.DesiredMovement.Y.Raw).Append(" pathIndex=").Append(m.PathIndex).Append(" state=").Append((byte)m.State).Append(" stuck=").Append(m.StuckTicks).Append(" compress=").Append(m.CompressionTicks);
            if(world.Entities.Navigation.TryGet(id,out NavigationAgent n))b.Append(" fp=").Append((byte)n.Footprint).Append(" layer=").Append((byte)n.Layer).Append(" target=").Append(n.Target.X.Raw).Append(',').Append(n.Target.Y.Raw).Append(" hasTarget=").Append(n.HasTarget?1:0).Append(" dirty=").Append(n.PathDirty?1:0).Append(" topo=").Append(n.PathTopologyVersion).Append(" age=").Append(n.RequestAge).Append(" cohort=").Append(n.Formation.CohortId).Append(" slot=").Append(n.Formation.SlotIndex).Append('/').Append(n.Formation.MemberCount).Append(" cols=").Append(n.Formation.Columns).Append(" reflowTick=").Append(n.Formation.LastReflowTick);
            if(world.Entities.Selectable.TryGet(id,out Selectable s))b.Append(" content=").Append(s.ContentType.Value).Append(" kind=").Append((byte)s.Kind);
            if(world.Entities.Vision.TryGet(id,out Vision v))b.Append(" vision=").Append(v.RadiusBuildCells);
            if(world.Entities.ResourceNode.TryGet(id,out ResourceNode resource))b.Append(" resourceType=").Append((byte)resource.Type).Append(" depositSize=").Append((byte)resource.DepositSize).Append(" remaining=").Append(resource.Remaining).Append('/').Append(resource.Capacity).Append(" visualState=").Append((byte)resource.VisualState);
            if(world.Entities.Worker.TryGet(id,out Worker worker))b.Append(" workerState=").Append((byte)worker.TaskState).Append(" resourceTarget=").Append(worker.ResourceTarget.Value).Append(" receiverTarget=").Append(worker.ReceiverTarget.Value).Append(" extractionTicks=").Append(worker.ExtractionTicks).Append('/').Append(worker.TicksPerOre);
            if(world.Entities.Builder.TryGet(id,out Builder builder))b.Append(" builderState=").Append((byte)builder.JobState).Append(" constructionTarget=").Append(builder.ConstructionTarget.Value);
            if(world.Entities.ResourceCarrier.TryGet(id,out ResourceCarrier carrier))b.Append(" cargoType=").Append((byte)carrier.Type).Append(" cargo=").Append(carrier.Amount).Append('/').Append(carrier.Capacity);
            if(world.Entities.ResourceReceiver.TryGet(id,out ResourceReceiver receiver))b.Append(" receiverType=").Append((byte)receiver.AcceptedType).Append(" pendingHauled=").Append(receiver.PendingHauledAmount).Append(" hqEmergency=").Append(receiver.IsHqEmergencyReceiver);
            if(world.Entities.ResourceBank.TryGet(id,out ResourceBank bank))b.Append(" bankType=").Append((byte)bank.Type).Append(" processed=").Append(bank.ProcessedAmount);
            if(world.Entities.Building.TryGet(id,out Building building))b.Append(" buildingType=").Append(building.Type.Value).Append(" anchor=").Append(building.AnchorX).Append(',').Append(building.AnchorY).Append(" orientation=").Append(building.Orientation).Append(" footprint=").Append(building.FootprintWidth).Append('x').Append(building.FootprintHeight).Append(" buildingState=").Append((byte)building.State);
            if(world.Entities.EnergyDomainMember.TryGet(id,out EnergyDomainMember energyMember))b.Append(" energyDomain=").Append(energyMember.DomainRoot.Value);
            if(world.Entities.WorksiteNode.TryGet(id,out WorksiteNode worksiteNode))b.Append(" worksiteNodeRadius=").Append(worksiteNode.ServiceRadius).Append(" worksiteNodeRoot=").Append(worksiteNode.ComponentRoot.Value);
            if(world.Entities.WorksiteMember.TryGet(id,out WorksiteMember worksiteMember))b.Append(" worksiteRoot=").Append(worksiteMember.ComponentRoot.Value);
            if(world.Entities.WorksiteComponent.TryGet(id,out WorksiteComponent worksiteComponent))b.Append(" worksiteNodes=").Append(worksiteComponent.NodeCount).Append(" worksiteMembers=").Append(worksiteComponent.MemberCount).Append(" worksiteRevision=").Append(worksiteComponent.TopologyRevision);
            if(world.Entities.Excavatable.TryGet(id,out Excavatable excavatable))b.Append(" excavatable=").Append(excavatable.MapFeatureId).Append(" stable=").Append(excavatable.StableId.Value).Append(" class=").Append((byte)excavatable.TerrainClass).Append(" state=").Append((byte)excavatable.State).Append(" energy=").Append(excavatable.RequiredEnergy);
            if(world.Entities.Deployment.TryGet(id,out Deployment deployment))b.Append(" deployment=").Append((byte)deployment.State);
            if(world.Entities.ForwardServiceProvider.TryGet(id,out ForwardServiceProvider serviceProvider))b.Append(" serviceRadius=").Append(serviceProvider.RadiusBuildCells).Append(" serviceActive=").Append(serviceProvider.IsActive?1:0);
            if(world.Entities.ForwardServiceMember.TryGet(id,out ForwardServiceMember serviceMember))b.Append(" serviceProvider=").Append(serviceMember.Provider.Value).Append(" serviceOwner=").Append(serviceMember.QueryOwner).Append(" serviceCell=").Append(serviceMember.QueryCellX).Append(',').Append(serviceMember.QueryCellY);
            if(world.Entities.MissionRefitState.TryGet(id,out MissionRefitState refitState))b.Append(" config=").Append((byte)refitState.CurrentConfiguration).Append(" ownedConfigs=").Append(refitState.OwnedConfigurationMask).Append(" configLock=").Append(refitState.ConfigurationLockTicks).Append(" surveyUnlocked=").Append(refitState.SurveyUnlocked?1:0);
            if(world.Entities.MissionRefitJob.TryGet(id,out MissionRefitJob refitJob))b.Append(" refit=").Append((byte)refitJob.OldConfiguration).Append('>').Append((byte)refitJob.NewConfiguration).Append(" refitTicks=").Append(refitJob.RemainingTicks).Append('/').Append(refitJob.TotalTicks).Append(" committed=").Append(refitJob.CommittedOre).Append('/').Append(refitJob.CommittedEnergy).Append(" refitProvider=").Append(refitJob.Provider.Value);
            if(world.Entities.ResonanceCore.TryGet(id,out ResonanceCore resonance))b.Append(" resonanceCommandCore=").Append(resonance.CommandCore.Value).Append(" resonanceSlots=").Append(resonance.CommittedSlotMask).Append(" resonanceDesired=").Append(resonance.DesiredCommittedCrystals).Append(" resonanceExpanded=").Append(resonance.ExpandedLatticeUnlocked?1:0).Append(" resonanceTransition=").Append((byte)resonance.TransitionKind).Append(':').Append(resonance.TransitionSlot).Append(':').Append(resonance.TransitionRemainingTicks).Append('/').Append(resonance.TransitionTotalTicks).Append(" resonanceBank=").Append(resonance.TransitionBank.Value);
            if(world.Entities.SurgeZone.TryGet(id,out SurgeZone surgeZone))b.Append(" surgeZone=").Append(surgeZone.RadiusBuildCells).Append(':').Append(surgeZone.BuildupRemainingTicks).Append(':').Append(surgeZone.ActiveRemainingTicks);
            if(world.Entities.SurgeReceiver.TryGet(id,out SurgeReceiver surgeReceiver))b.Append(" surgedBy=").Append(surgeReceiver.ActiveZone.Value);
            if(world.Entities.TubeStation.TryGet(id,out TubeStation tubeStation))b.Append(" tubeStationRoot=").Append(tubeStation.ComponentRoot.Value).Append(" tubeConnections=").Append(tubeStation.ConnectionCount).Append('/').Append(tubeStation.ConnectionLimit).Append(" tubeRedundant=").Append(tubeStation.RedundantRoutingUnlocked?1:0).Append(" tubeCapacity=").Append(tubeStation.HypersledThroughputUnlocked?3:2);
            if(world.Entities.TubeLink.TryGet(id,out TubeLink tubeLink))b.Append(" tubeLink=").Append(tubeLink.EndpointA.Value).Append('>').Append(tubeLink.EndpointB.Value).Append(" tubeLinkRoot=").Append(tubeLink.ComponentRoot.Value).Append(" tubeLength=").Append(tubeLink.LengthBuildCells).Append(" tubeDemand=").Append(tubeLink.EnergyDemandPerSecond).Append(" tubeOperational=").Append(tubeLink.IsOperational?1:0);
            if(world.Entities.TubeComponent.TryGet(id,out TubeComponent tubeComponent))b.Append(" tubeStations=").Append(tubeComponent.StationCount).Append(" tubeLinks=").Append(tubeComponent.OperationalLinkCount).Append(" tubeRevision=").Append(tubeComponent.TopologyRevision);
            if(world.Entities.TubeTransfer.TryGet(id,out TubeTransfer tubeTransfer)){b.Append(" tubeTransfer=").Append(tubeTransfer.Origin.Value).Append('>').Append(tubeTransfer.Destination.Value).Append(" tubeState=").Append((byte)tubeTransfer.State).Append(" tubeTicks=").Append(tubeTransfer.RemainingTicks).Append('/').Append(tubeTransfer.TotalTravelTicks).Append(" tubeEdge=").Append(tubeTransfer.CurrentEdgeIndex).Append(" tubeExitWait=").Append(tubeTransfer.ExitWaitTicks).Append(" tubeArrivalOrder=").Append(tubeTransfer.HasArrivalMoveOrder?1:0).Append('@').Append(tubeTransfer.ArrivalMoveTarget.X.Raw).Append(',').Append(tubeTransfer.ArrivalMoveTarget.Y.Raw);if(world.TubeTransitRoutes.TryGetValue(id.Value,out TubeTransitRoute transitRoute)){b.Append(" tubeTransitLinks=");for(int ti=0;ti<transitRoute.Links.Count;ti++)b.Append(ti==0?'#':'>').Append(transitRoute.Links[ti].Value);}}
            if(world.Entities.Stability.TryGet(id,out Stability stability))b.Append(" stabilityUntil=").Append(stability.UntilTick).Append(" stabilityRemaining=").Append(DisplacementSystem.RemainingStabilityTicks(world,id));
            if(world.Entities.ConstructionSite.TryGet(id,out ConstructionSite site))b.Append(" builder=").Append(site.AssignedBuilder.Value).Append(" fundingBank=").Append(site.FundingBank.Value).Append(" reservedOre=").Append(site.ReservedOre).Append(" consumedOre=").Append(site.ConsumedOre).Append(" requiredEnergy=").Append(site.RequiredEnergy).Append(" reservedEnergy=").Append(site.ReservedEnergy).Append(" consumedEnergy=").Append(site.ConsumedEnergy).Append(" constructionTicks=").Append(site.ProgressTicks).Append('/').Append(site.RequiredTicks);
            if(world.Entities.Production.TryGet(id,out Production production)){b.Append(" productionCount=").Append(production.Count).Append(" spawnBlocked=").Append(production.SpawnBlocked?1:0).Append(" rally=").Append(production.HasRallyPoint?1:0).Append('@').Append(production.RallyPoint.X.Raw).Append(',').Append(production.RallyPoint.Y.Raw);for(int pi=0;pi<production.Count;pi++){ProductionQueueItem item=production.Get(pi);b.Append(" item").Append(pi).Append('=').Append(item.UnitType.Value).Append(':').Append(item.RemainingTicks).Append('/').Append(item.TotalTicks).Append(':').Append(item.ReservedOre);}}
            if(world.TryGetQueue(id,out UnitCommandQueue q))b.Append(" queue=").Append(q.Count);
            RouteCorridor? corridor=world.GetCorridor(id);if(corridor!=null)b.Append(" corridorCells=").Append(corridor.Cells.Count).Append(" corridorTopo=").Append(corridor.TopologyVersion);
            TubeRoute? tubeRoute=world.GetTubeRoute(id);if(tubeRoute!=null){b.Append(" tubeRouteCells=").Append(tubeRoute.Cells.Count);for(int ti=0;ti<tubeRoute.Cells.Count;ti++)b.Append('@').Append(tubeRoute.Cells[ti].X).Append(',').Append(tubeRoute.Cells[ti].Y);}
            b.AppendLine();
        }
        b.Append("pendingCommands=").Append(world.Commands.Count).Append(" stateHash=").Append(StateHasher.HashHex(world)).AppendLine();
        return b.ToString();
    }

    public static string FirstDifference(string expected,string actual)
    {
        string[] a=expected.Replace("\r",string.Empty).Split('\n');string[] b=actual.Replace("\r",string.Empty).Split('\n');
        int n=a.Length<b.Length?a.Length:b.Length;
        for(int i=0;i<n;i++)if(!string.Equals(a[i],b[i],System.StringComparison.Ordinal))return "line="+(i+1)+" expected=["+a[i]+"] actual=["+b[i]+"]";
        return a.Length==b.Length?"no textual state difference":"line-count expected="+a.Length+" actual="+b.Length;
    }
}
}
